### PR TITLE
This commit provides a baseline scaffolding

### PR DESCRIPTION
**Pull request by johnbaldwin**
This commit provides a  minimal Django reusable app to provide APIs using Django REST Framework. It is generic enough to require only minimal changes to be used as a template for other API packages

It is not intended to be a working app, but running `tox` passes in my dev environment ;). I wanted to make this commit be somewhat generic. After we merge this into master, then I will begin work on the enrollment api 

* Boilerplate `appsembler_apis` django reusable app
* Tests: One working test modules, `test_apps.py` passes
  * pytest and tox runs and passes

### Directory structure

* https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure
* https://docs.pytest.org/en/latest/goodpractices.html#tests-outside-application-code

### Models for project structure

* Django REST Framework
* Figures

### CODE REVIEW

**Comment by OmarIthawi** [comment]
@johnbaldwin did you use https://github.com/edx/cookiecutter-django-app ? I hope so, it's such a time-saver.

**Comment by johnbaldwin** [comment]
[(5) Stand up appsembler-apis django reusable app scaffolding](https://trello.com/c/jRypoXSe/4074-5-stand-up-appsembler-apis-django-reusable-app-scaffolding)

**Comment by johnbaldwin** [comment]
@OmarIthawi No, I didn't use cookie cutter. I based the structure on Django REST Framework and Figures. Would have been nice to know about edX's cookie cutter before I started. But here we are.

**Comment by OmarIthawi** [comment]
@johnbaldwin Two questions here, if we're building something we'd eventually throw away, why not building it next to the Registration API within the platform?

Second, if it's not a show stopper, please do use the edX cookie cutter as it's a lot easier to maintain and reason about once you get used to it.

**Comment by johnbaldwin** [comment]
@OmarIthawi I might have time tomorrow morning to try out this cookie-cutter. Have you already used it?

But are we approaching better is the enemy of good enough?

**Comment by OmarIthawi** [comment]
@johnbaldwin if we're looking for good enough, then definitly we should _not_ be using a seperate repo. Let's please add the API within the edX Platform just like we did in https://github.com/appsembler/edx-platform/pull/286 . Using a separate repo, is an overkill for the enrollment API we'd like to have.

**Review by OmarIthawi — COMMENTED** [review]
As discussed. Please stuff it in the Open edX repo.

**Comment by thraxil** [comment]
If a decision was made on this, can we remove the PR?

**Comment by OmarIthawi** [comment]
Thanks @thraxil! I'm closing this. Closing is cheap, so is re-opening just in case we needed it in the future.

cc: @johnbaldwin

**Pull request closed without merging**
